// Mock data for development without Supabase connection
// Mirrors the seed data from 002_seed_kowex_servers.sql

import type { McpServer, McpTool } from "@agent-hub/db";

export const MOCK_SERVERS: McpServer[] = [
  {
    id: "srv-001",
    slug: "ucetni-prevodnik",
    name: "Účetní Převodník",
    description: "Czech accounting format converter — transforms between ISDOC, EDI, and standard EU invoice formats.",
    long_description: "The essential tool for Czech and EU accounting workflows. Convert invoices between ISDOC, ISDOCX, EDI (EDIFACT), UBL 2.1, and Factur-X formats. Validates VAT IDs against VIES, checks CZ-specific fields, and ensures compliance with Czech accounting law.",
    category: "finance",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 9.90,
    free_tier_calls: 200,
    trust_score: 9.2,
    is_verified: true,
    is_featured: true,
    total_tools: 4,
    total_calls: 15230,
    avg_response_ms: 120,
    uptime_percent: 99.9,
    version: "1.2.0",
    tags: ["accounting", "czech", "isdoc", "invoice", "eu-compliance"],
    documentation_url: "https://docs.agentforge.eu/ucetni-prevodnik",
    source_url: null,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-002",
    slug: "phantom-office",
    name: "PhantomOffice",
    description: "AI-powered virtual office assistant — handles scheduling, document generation, and team coordination.",
    long_description: "PhantomOffice is an autonomous office management suite. It handles meeting scheduling with timezone awareness, generates professional documents from templates, manages team task queues, and provides natural-language access to company knowledge bases.",
    category: "productivity",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 19.90,
    free_tier_calls: 100,
    trust_score: 8.8,
    is_verified: true,
    is_featured: true,
    total_tools: 3,
    total_calls: 8420,
    avg_response_ms: 250,
    uptime_percent: 99.7,
    version: "2.0.0",
    tags: ["office", "scheduling", "documents", "ai-assistant", "multilingual"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-003",
    slug: "dataforge",
    name: "DataForge",
    description: "Serverless data pipeline builder — ETL, transformations, and analytics for AI agent workflows.",
    long_description: "Build and run data pipelines without infrastructure. DataForge handles CSV/JSON/Parquet ingestion, SQL transformations, data quality checks, and exports to any format.",
    category: "data",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 14.90,
    free_tier_calls: 150,
    trust_score: 8.5,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 5100,
    avg_response_ms: 340,
    uptime_percent: 99.5,
    version: "1.5.0",
    tags: ["etl", "data-pipeline", "analytics", "csv", "sql", "serverless"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-004",
    slug: "legal-eagle",
    name: "LegalEagle",
    description: "AI legal document analyzer — contract review, risk detection, and compliance checking for EU law.",
    long_description: "LegalEagle analyzes legal documents with focus on EU and Czech law. It identifies risky clauses, checks GDPR compliance, compares contracts against standard templates, and generates plain-language summaries.",
    category: "legal",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "paid",
    price_monthly: 29.90,
    free_tier_calls: 50,
    trust_score: 9.0,
    is_verified: true,
    is_featured: true,
    total_tools: 3,
    total_calls: 3200,
    avg_response_ms: 890,
    uptime_percent: 99.8,
    version: "1.0.0",
    tags: ["legal", "contracts", "gdpr", "compliance", "eu-law"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-005",
    slug: "breeder-os",
    name: "BreederOS",
    description: "Professional breeding management — genetics calculator, pedigree tracking, and health records.",
    long_description: "Complete breeding management platform for professional breeders. Calculate genetic compatibility (COI), generate pedigree charts, track health screenings.",
    category: "ai",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 12.90,
    free_tier_calls: 100,
    trust_score: 8.0,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 2100,
    avg_response_ms: 200,
    uptime_percent: 99.6,
    version: "1.0.0",
    tags: ["breeding", "genetics", "pedigree", "health", "animals"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-006",
    slug: "svatby-app",
    name: "SvatbyApp",
    description: "AI wedding planner — venue matching, budget optimization, and guest management for Czech weddings.",
    long_description: "Complete AI-powered wedding planning assistant tailored for Czech and Slovak markets.",
    category: "productivity",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 7.90,
    free_tier_calls: 200,
    trust_score: 7.5,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 1800,
    avg_response_ms: 180,
    uptime_percent: 99.4,
    version: "1.0.0",
    tags: ["wedding", "planning", "events", "czech", "venues"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-02-12T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-007",
    slug: "eu-compliance-bot",
    name: "EUComplianceBot",
    description: "Automated EU regulatory compliance checking — GDPR, AI Act, NIS2, and DORA readiness assessments.",
    long_description: "Stay compliant with evolving EU regulations. Checks your systems against GDPR, the EU AI Act, NIS2 Directive, and DORA requirements.",
    category: "legal",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "paid",
    price_monthly: 39.90,
    free_tier_calls: 30,
    trust_score: 9.5,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 4500,
    avg_response_ms: 1200,
    uptime_percent: 99.9,
    version: "2.1.0",
    tags: ["compliance", "gdpr", "ai-act", "nis2", "dora", "eu-regulation"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-008",
    slug: "mailforge",
    name: "MailForge",
    description: "AI email campaign engine — personalized content, A/B testing, and deliverability optimization.",
    long_description: "Create and send high-converting email campaigns with AI. Generates personalized content, optimizes send times, runs A/B tests automatically.",
    category: "communication",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 24.90,
    free_tier_calls: 100,
    trust_score: 8.2,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 6700,
    avg_response_ms: 300,
    uptime_percent: 99.7,
    version: "1.3.0",
    tags: ["email", "marketing", "campaigns", "personalization"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-009",
    slug: "code-review-bot",
    name: "CodeReviewBot",
    description: "AI code review assistant — security scanning, performance analysis, and style enforcement.",
    long_description: "Automated code review powered by AI. Scans PRs for security vulnerabilities, identifies performance bottlenecks, checks coding style consistency.",
    category: "development",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 19.90,
    free_tier_calls: 100,
    trust_score: 8.7,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 9800,
    avg_response_ms: 450,
    uptime_percent: 99.8,
    version: "1.1.0",
    tags: ["code-review", "security", "performance", "github"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-01-25T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "srv-010",
    slug: "translate-hub",
    name: "TranslateHub",
    description: "EU-focused translation engine — supports all 24 EU languages with domain-specific terminology.",
    long_description: "High-quality translation engine optimized for EU languages and business terminology. Handles document translation, glossary management, and localization workflows.",
    category: "communication",
    icon_url: null,
    endpoint_url: null,
    owner_id: null,
    agent_id: null,
    pricing_model: "freemium",
    price_monthly: 14.90,
    free_tier_calls: 300,
    trust_score: 8.3,
    is_verified: true,
    is_featured: false,
    total_tools: 3,
    total_calls: 12400,
    avg_response_ms: 150,
    uptime_percent: 99.9,
    version: "2.0.0",
    tags: ["translation", "localization", "eu-languages", "business"],
    documentation_url: null,
    source_url: null,
    created_at: "2026-01-18T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
];

export const MOCK_TOOLS: Record<string, McpTool[]> = {
  "ucetni-prevodnik": [
    { id: "t-001", server_id: "srv-001", name: "convert_invoice", description: "Convert invoice between formats (ISDOC, UBL, Factur-X, EDI)", input_schema: { type: "object", properties: { source_format: { type: "string", enum: ["isdoc","ubl","facturx","edi"] }, target_format: { type: "string", enum: ["isdoc","ubl","facturx","edi"] }, invoice_data: { type: "string" } }, required: ["source_format","target_format","invoice_data"] }, output_schema: { type: "object", properties: { converted_document: { type: "string" }, format: { type: "string" }, validation_passed: { type: "boolean" } } }, example_input: { source_format: "isdoc", target_format: "ubl", invoice_data: "PD94bWw..." }, example_output: { converted_document: "PD94bWw...", format: "ubl", validation_passed: true }, is_active: true, avg_response_ms: 120, created_at: "2026-01-15T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    { id: "t-002", server_id: "srv-001", name: "validate_vat_id", description: "Validate EU VAT ID against VIES database", input_schema: { type: "object", properties: { vat_id: { type: "string" } }, required: ["vat_id"] }, output_schema: { type: "object", properties: { valid: { type: "boolean" }, company_name: { type: "string" }, country: { type: "string" } } }, example_input: { vat_id: "CZ12345678" }, example_output: { valid: true, company_name: "KOWEX Co. s.r.o.", country: "CZ" }, is_active: true, avg_response_ms: 80, created_at: "2026-01-15T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    { id: "t-003", server_id: "srv-001", name: "validate_invoice", description: "Validate invoice against Czech accounting law and EU standards", input_schema: { type: "object", properties: { format: { type: "string" }, invoice_data: { type: "string" } }, required: ["format","invoice_data"] }, output_schema: { type: "object", properties: { valid: { type: "boolean" }, errors: { type: "array" }, warnings: { type: "array" } } }, example_input: { format: "isdoc", invoice_data: "PD94bWw..." }, example_output: { valid: true, errors: [], warnings: ["Missing optional field: OrderReference"] }, is_active: true, avg_response_ms: 95, created_at: "2026-01-15T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    { id: "t-004", server_id: "srv-001", name: "extract_invoice_data", description: "Extract structured data from invoice document (OCR + parsing)", input_schema: { type: "object", properties: { document: { type: "string" }, language: { type: "string", default: "cs" } }, required: ["document"] }, output_schema: { type: "object", properties: { invoice_number: { type: "string" }, total: { type: "number" }, currency: { type: "string" }, vendor: { type: "object" } } }, example_input: { document: "JVBERi0...", language: "cs" }, example_output: { invoice_number: "FV-2026-001", total: 12100, currency: "CZK", vendor: { name: "KOWEX Co.", ico: "12345678" } }, is_active: true, avg_response_ms: 250, created_at: "2026-01-15T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  ],
};

export function getMockServer(slug: string): McpServer | undefined {
  return MOCK_SERVERS.find((s) => s.slug === slug);
}

export function getMockTools(slug: string): McpTool[] {
  return MOCK_TOOLS[slug] ?? [];
}
