import { type NextRequest } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { apiSuccess, apiError } from "@/lib/api/response";
import { validateApiKey } from "@/lib/api/auth";

function getServiceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) return null;
  return createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

/**
 * POST /api/v1/webmcp/snippet — Generate WebMCP integration snippet
 *
 * Auth: X-API-Key header
 * Body: {
 *   server_id: string,           — the server to generate snippet for
 *   website_url: string,         — the website that will host WebMCP tools
 *   api_type?: "declarative" | "imperative" | "both"
 * }
 *
 * Returns ready-to-paste JavaScript code for WebMCP integration.
 */
export async function POST(request: NextRequest) {
  const key = await validateApiKey(request);
  if (!key) {
    return apiError("API key required (X-API-Key header)", 401);
  }

  const supabase = getServiceClient();
  if (!supabase) {
    return apiError("Service unavailable", 503);
  }

  let body: {
    server_id: string;
    website_url: string;
    api_type?: "declarative" | "imperative" | "both";
  };

  try {
    body = await request.json();
  } catch {
    return apiError("Invalid JSON body", 400);
  }

  if (!body.server_id || !body.website_url) {
    return apiError("'server_id' and 'website_url' are required", 400);
  }

  // Get server and its tools
  const { data: server } = await supabase
    .from("mcp_servers")
    .select("id, name, slug, description, category")
    .eq("id", body.server_id)
    .single();

  if (!server) {
    return apiError("Server not found", 404);
  }

  const { data: tools } = await supabase
    .from("mcp_tools")
    .select("name, description, input_schema, output_schema")
    .eq("server_id", server.id)
    .eq("is_active", true);

  const apiType = body.api_type ?? "imperative";

  // Generate the snippet
  let snippet: string;

  if (apiType === "declarative" || apiType === "both") {
    snippet = generateDeclarativeSnippet(server, tools ?? []);
  } else {
    snippet = generateImperativeSnippet(
      server,
      tools ?? [],
      body.website_url
    );
  }

  if (apiType === "both") {
    snippet +=
      "\n\n// --- Imperative API (for complex interactions) ---\n\n";
    snippet += generateImperativeSnippet(
      server,
      tools ?? [],
      body.website_url
    );
  }

  // Update server with WebMCP config
  await supabase
    .from("mcp_servers")
    .update({
      webmcp_config: {
        website_url: body.website_url,
        api_type: apiType,
        requires_auth: false,
        chrome_version: "146",
      },
      install_type: "webmcp",
      access_types: ["api", "webmcp"],
    })
    .eq("id", server.id);

  return apiSuccess({
    server_id: server.id,
    server_name: server.name,
    api_type: apiType,
    tools_count: (tools ?? []).length,
    snippet,
    instructions: [
      "1. Add this script to your website's HTML (before </body>)",
      "2. The tools will be automatically available to AI agents via Chrome 146+ WebMCP",
      "3. Agents discover your tools via AgentForge registry or /.well-known/agentforge.json",
      `4. Test with Chrome Canary: chrome://flags → enable "WebMCP"`,
    ],
  });
}

function generateImperativeSnippet(
  server: Record<string, unknown>,
  tools: Array<Record<string, unknown>>,
  websiteUrl: string
): string {
  const toolRegistrations = tools
    .map((tool) => {
      const params = tool.input_schema as Record<string, unknown>;
      const paramEntries = params?.properties
        ? Object.entries(params.properties as Record<string, unknown>)
            .map(([key, val]) => {
              const v = val as Record<string, unknown>;
              return `    ${key}: { type: "${v.type ?? "string"}", description: "${v.description ?? key}" }`;
            })
            .join(",\n")
        : '    input: { type: "object", description: "Tool input" }';

      return `  navigator.modelContext.registerTool({
    name: "${tool.name}",
    description: "${tool.description}",
    parameters: {
${paramEntries}
    },
    handler: async (params) => {
      // TODO: Implement your ${tool.name} logic here
      // This replaces dozens of screenshot/DOM interactions with one structured call
      const result = await your${capitalize(tool.name as string)}Handler(params);
      return result;
    }
  });`;
    })
    .join("\n\n");

  return `// AgentForge WebMCP Integration — ${server.name}
// Website: ${websiteUrl}
// Generated by AgentForge (agentforge.community)
//
// Add this script to your website to expose tools to AI agents via WebMCP.
// Requires Chrome 146+ with WebMCP enabled.

(function() {
  if (!navigator.modelContext) {
    console.log('[AgentForge] WebMCP not available — Chrome 146+ required');
    return;
  }

  // Register tools with WebMCP
${toolRegistrations}

  console.log('[AgentForge] ${tools.length} WebMCP tools registered for ${server.name}');
})();`;
}

function generateDeclarativeSnippet(
  server: Record<string, unknown>,
  tools: Array<Record<string, unknown>>
): string {
  const formExamples = tools
    .slice(0, 3)
    .map((tool) => {
      return `<!-- WebMCP Tool: ${tool.name} -->
<form data-tool-name="${tool.name}" data-tool-description="${tool.description}">
  <input name="query" type="text" placeholder="Search..." />
  <button type="submit">Search</button>
</form>`;
    })
    .join("\n\n");

  return `<!-- AgentForge WebMCP Declarative Integration — ${server.name} -->
<!-- Add data-tool-name and data-tool-description to existing forms -->

${formExamples}`;
}

function capitalize(s: string): string {
  return s
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}
